# Generated by Django 3.0.7 on 2020-06-14 14:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200614_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='access_until',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
